server:
  port: 5555   # 启动第2个消费者的时候改为5555端口号
spring:
  activemq:
    broker-url: tcp://192.168.239.13:61616
    user: admin
    password: admin
  jms:
    pub-sub-domain: true

myTopic: boot-activemq-topic
